settings:
  recovery:
    index: true
    events: false
    tools: false
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: true
  port: 3000
  host: localhost
schema:
- name: realize
  path: .
  commands:
    generate:
      status: true
    install:
      status: true
    vet:
      status: true
    test:
      status: true
    fmt:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - html
    - css
    - js
    ignored_paths:
    - .git
    - .realize
    - .idea
    - vendor
    - realize/assets
    - realize/bindata.go
